spring:
  application:
    name: channel-eureka
  security:
      user:
        name: miaoweiwei
        password: Aa888888
server:
  port: 8761

eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://miaoweiwei:Aa888888@localhost:8762/eureka/

